// GENERATED by tools/build_aozora_catalog.py, which rewrites the count line
// — do not edit by hand.

/// Works in the bundled Aozora Bunko catalog (`assets/free_books/aozora.json`),
/// for copy that needs the number without parsing the catalog.
const int aozoraWorkCount = 17229;
