// Regenerates lib/core/utils/jlpt_kanji_levels.dart.
//
// Usage:
//   curl -sL -o kanji-data.json \
//     https://raw.githubusercontent.com/davidluzgouveia/kanji-data/master/kanji.json
//   dart tool/generate_jlpt_kanji_levels.dart kanji-data.json
//
// Level assignment, in order:
//   1. jlpt_new from the dataset (Jonathan Waller's N5..N1 kanji lists).
//   2. Hand-maintained overrides below — the JLPT kanji lists predate the
//      2010 joyo reform, so additions like 誰 carry no level even though
//      their common vocabulary is N5. Levels here follow the JLPT level of
//      the kanji's most common word.
//   3. Joyo kanji (grade <= 8) still without a level -> N1: an N1 reader is
//      expected to know joyo kanji, so they only get furigana below the
//      "above N1" threshold.
//   4. Everything else is omitted -> the runtime treats it as hardest
//      (annotated at every threshold): non-joyo fiction kanji like 囁.

import 'dart:convert';
import 'dart:io';

/// 2010 joyo additions whose common vocabulary is far easier than their
/// absence from the JLPT lists suggests. Keyed by kanji, valued N5=5..N1=1.
const Map<String, int> overrides = {
  '誰': 5, // だれ
  '頃': 5, // 〜頃
  '鍵': 4, // かぎ
  '貼': 4, // 貼る
  '俺': 3,
  '匂': 3, // 匂い
  '叱': 3, // 叱る
  '喉': 3, // のど
  '尻': 3,
  '蹴': 3, // 蹴る
  '膝': 3, // ひざ
  '肘': 3, // ひじ
  '爪': 3, // つめ
  '枕': 3, // まくら
  '拭': 3, // 拭く
  '鍋': 3, // なべ
  '餅': 3, // もち
  '麺': 3,
  '丼': 3,
  '挨': 3, // 挨拶
  '拶': 3, // 挨拶
  '袖': 3, // そで
  '柿': 3, // かき
  '蜂': 3, // はち
};

void main(List<String> args) {
  final jsonPath = args.isNotEmpty ? args[0] : 'kanji-data.json';
  final outPath = args.length > 1
      ? args[1]
      : 'lib/core/utils/jlpt_kanji_levels.dart';

  final data =
      jsonDecode(File(jsonPath).readAsStringSync()) as Map<String, dynamic>;
  final levels = <int, int>{};
  var joyoFallbacks = 0;
  data.forEach((kanji, info) {
    if (kanji.runes.length != 1) return;
    final map = info as Map<String, dynamic>;
    final listed = map['jlpt_new'];
    final grade = map['grade'];
    if (listed is int) {
      levels[kanji.runes.single] = listed;
    } else if (grade is int && grade <= 8) {
      levels[kanji.runes.single] = 1;
      joyoFallbacks++;
    }
  });
  overrides.forEach((kanji, level) {
    levels[kanji.runes.single] = level;
  });

  final counts = <int, int>{};
  for (final level in levels.values) {
    counts[level] = (counts[level] ?? 0) + 1;
  }
  final sorted = levels.entries.toList()
    ..sort((a, b) => a.key.compareTo(b.key));

  final buf = StringBuffer()
    ..writeln(
      '// GENERATED by tool/generate_jlpt_kanji_levels.dart — do not edit by',
    )
    ..writeln('// hand; adjust the overrides in the tool and regenerate.')
    ..writeln('//')
    ..writeln('// Kanji → JLPT level from the jlpt_new field of')
    ..writeln('// https://github.com/davidluzgouveia/kanji-data (fetched')
    ..writeln('// 2026-08-08), which aggregates KANJIDIC2 (EDRDG licence) and')
    ..writeln("// Jonathan Waller's JLPT resources (www.tanos.co.uk, CC BY),")
    ..writeln('// plus hand overrides for 2010 joyo additions and an N1')
    ..writeln('// fallback for unlisted joyo kanji (see the tool header).')
    ..writeln('//')
    ..write('// Entries per level:');
  for (var level = 5; level >= 1; level--) {
    buf.write(' N$level=${counts[level] ?? 0}');
  }
  buf
    ..writeln(' (total ${levels.length},')
    ..writeln('// of which $joyoFallbacks unlisted-joyo N1 fallbacks).')
    ..writeln('//')
    ..writeln('// Data only — the lookup that reads it is')
    ..writeln('// wordNeedsFuriganaAboveLevel in japanese_text.dart.')
    ..writeln()
    ..writeln('/// JLPT level per kanji rune: N5 = 5 (easiest) … N1 = 1')
    ..writeln('/// (hardest). Kanji absent from the map are non-joyo and')
    ..writeln('/// treated as harder than N1.')
    ..writeln('const Map<int, int> jlptKanjiLevel = {');
  for (final entry in sorted) {
    final char = String.fromCharCode(entry.key);
    buf.writeln(
      '  0x${entry.key.toRadixString(16).toUpperCase()}: ${entry.value}, // $char',
    );
  }
  buf.writeln('};');

  File(outPath).writeAsStringSync(buf.toString());
  stdout.writeln(
    'Wrote ${levels.length} entries ($joyoFallbacks joyo fallbacks, '
    '${overrides.length} overrides) to $outPath',
  );
}
