#!/usr/bin/env python3
"""Generate the PDF fixtures for the PDF-import tests.

Writes integration_test/shared/pdf_fixtures.dart (base64 constants, so the
fixtures reach the device with the test) — re-run after changing this file:

    pip install -r tools/requirements-free-books.txt
    python tools/make_pdf_fixtures.py

The text PDF mimics NPO Tadoku Supporters' graded readers without copying
them: a horizontal page and a vertical page, every glyph placed on its own
(vertical books do this), with furigana at half size beside or above the
kanji it reads, and a page number. The font is PyMuPDF's bundled CJK
fallback font (Droid Sans Fallback, Apache-2.0), embedded as a subset with
a ToUnicode map — PDFium reads no text from non-embedded CJK fonts. The
scanned PDF is two pages that are only images, with no text layer.
"""

from __future__ import annotations

import base64
import io
from pathlib import Path

import pymupdf

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "integration_test" / "shared" / "pdf_fixtures.dart"
SIZE = 20
WIDTH, HEIGHT = 420, 595  # A5 in points

# (base, reading or None) runs; the sentence repeats to fill the lines.
SENTENCE = [("今日", "きょう"), ("は", None), ("学校", "がっこう"), ("で", None), ("日本語", "にほんご"), ("を勉強します。", None)]


def _runs(repeat: int):
    for _ in range(repeat):
        yield from SENTENCE


def _put(page: pymupdf.Page, char: str, x: float, top: float, size: float) -> None:
    """One glyph whose em box starts at (x, top); PyMuPDF places by baseline."""
    page.insert_text((x, top + size * 0.88), char, fontsize=size, fontname="cjk", fontfile=None)


def horizontal_page(page: pymupdf.Page) -> None:
    x, top = 30.0, 60.0
    for base, reading in _runs(12):
        run = len(base) * SIZE
        if x + run > WIDTH - 30:
            x, top = 30.0, top + SIZE * 2
        if reading:
            offset = (run - len(reading) * SIZE / 2) / 2
            for i, char in enumerate(reading):
                _put(page, char, x + offset + i * SIZE / 2, top - SIZE / 2, SIZE / 2)
        for char in base:
            _put(page, char, x, top, SIZE)
            x += SIZE
    _put(page, "1", WIDTH / 2, HEIGHT - 30, SIZE / 2)


def vertical_page(page: pymupdf.Page) -> None:
    x, top = WIDTH - 60.0, 40.0
    for base, reading in _runs(12):
        run = len(base) * SIZE
        if top + run > HEIGHT - 50:
            x, top = x - SIZE * 2, 40.0
        for char in base:
            _put(page, char, x, top, SIZE)
            top += SIZE
        if reading:
            # Readings come after their run in drawing order, as in Tadoku's PDFs.
            start = top - run + (run - len(reading) * SIZE / 2) / 2
            for i, char in enumerate(reading):
                _put(page, char, x + SIZE, start + i * SIZE / 2, SIZE / 2)
    _put(page, "2", WIDTH / 2, HEIGHT - 30, SIZE / 2)


def text_pdf() -> bytes:
    document = pymupdf.open()
    for draw in (horizontal_page, vertical_page):
        page = document.new_page(width=WIDTH, height=HEIGHT)
        page.insert_font(fontname="cjk", fontbuffer=pymupdf.Font("cjk").buffer)
        draw(page)
    document.subset_fonts()
    return document.tobytes(garbage=4, deflate=True, no_new_id=True)


def scanned_pdf() -> bytes:
    """Two pages that are only pictures, like a scanned book."""
    pixmap = pymupdf.Pixmap(pymupdf.csGRAY, pymupdf.IRect(0, 0, 210, 297), False)
    pixmap.clear_with(255)
    for row in range(20, 280, 14):
        pixmap.set_rect(pymupdf.IRect(20, row, 190, row + 6), (60,))
    png = pixmap.tobytes("png")
    document = pymupdf.open()
    for _ in range(2):
        page = document.new_page(width=WIDTH, height=HEIGHT)
        page.insert_image(page.rect, stream=png)
    return document.tobytes(garbage=4, deflate=True, no_new_id=True)


def dart_constant(name: str, data: bytes, doc: str) -> str:
    encoded = base64.b64encode(data).decode("ascii")
    chunks = [encoded[i:i + 76] for i in range(0, len(encoded), 76)]
    body = "\n".join(f"  '{chunk}'" for chunk in chunks)
    return f"/// {doc}\nconst {name} =\n{body};\n"


def main() -> None:
    OUT.write_text(
        "// GENERATED by tools/make_pdf_fixtures.py — do not edit by hand.\n\n"
        + dart_constant(
            "textPdfBase64",
            text_pdf(),
            "Page 1 horizontal, page 2 vertical; glyph by glyph, half-size furigana.",
        )
        + "\n"
        + dart_constant("scannedPdfBase64", scanned_pdf(), "Two image-only pages, no text layer."),
        encoding="utf-8",
        newline="\n",
    )
    print(f"wrote {OUT.relative_to(REPO)}")


if __name__ == "__main__":
    main()
