"""Writes integration_test/shared/test_fonts.dart: two tiny TrueType fonts
made here, from box glyphs (no third-party font data), whose 山 is 2 em
wide in one and 3 em in the other, so a test can tell from a measured
width which font the reader used.

Run from the repo root: python tools/make_test_font.py (needs fontTools),
then dart format integration_test/shared/test_fonts.dart.
"""

from io import BytesIO
from pathlib import Path

from fontTools.fontBuilder import FontBuilder
from fontTools.pens.ttGlyphPen import TTGlyphPen

UNITS_PER_EM = 1000
OUT = Path(__file__).resolve().parent.parent / "integration_test" / "shared" / "test_fonts.dart"


def box(advance):
    pen = TTGlyphPen(None)
    pen.moveTo((50, 0))
    pen.lineTo((50, 700))
    pen.lineTo((advance - 50, 700))
    pen.lineTo((advance - 50, 0))
    pen.closePath()
    return pen.glyph()


def build(family, advance):
    fb = FontBuilder(UNITS_PER_EM, isTTF=True)
    fb.setupGlyphOrder([".notdef", "shan"])
    fb.setupCharacterMap({0x5C71: "shan"})  # 山
    fb.setupGlyf({".notdef": box(500), "shan": box(advance)})
    fb.setupHorizontalMetrics({".notdef": (500, 50), "shan": (advance, 50)})
    fb.setupHorizontalHeader(ascent=800, descent=-200)
    fb.setupNameTable({"familyName": family, "styleName": "Regular"})
    fb.setupOS2(sTypoAscender=800, sTypoDescender=-200, usWinAscent=800, usWinDescent=200)
    fb.setupPost()
    out = BytesIO()
    fb.save(out)
    return out.getvalue()


def dart_list(name, data):
    rows = [", ".join(str(b) for b in data[i:i + 20]) for i in range(0, len(data), 20)]
    body = ",\n  ".join(rows)
    return f"const {name} = <int>[\n  {body},\n];\n"


def main():
    wide = build("Mekuru Test Wide", 2 * UNITS_PER_EM)
    wider = build("Mekuru Test Wider", 3 * UNITS_PER_EM)
    OUT.write_text(
        "// Generated by tools/make_test_font.py. Do not edit.\n"
        "//\n"
        "// Two tiny TrueType fonts made by that script from box glyphs (no\n"
        "// third-party font data): 山 is 2 em wide in [testFontWide] and 3 em\n"
        "// in [testFontWider].\n\n"
        + dart_list("testFontWide", wide)
        + "\n"
        + dart_list("testFontWider", wider),
        encoding="utf-8",
        newline="\n",
    )


if __name__ == "__main__":
    main()
